-- MySQL Script generated by MySQL Workbench
-- Wed Sep  4 17:00:05 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema proyectodb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema proyectodb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `proyectodb` DEFAULT CHARACTER SET utf8 ;
USE `proyectodb` ;

-- -----------------------------------------------------
-- Table `proyectodb`.`Anuncios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyectodb`.`Anuncios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `texto` VARCHAR(500) NOT NULL,
  `imagen` BLOB NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyectodb`.`Detalle_Pedidos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyectodb`.`Detalle_Pedidos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `pedidoId` INT NOT NULL,
  `productoId` INT NOT NULL,
  `cantidad` FLOAT NOT NULL,
  `total` FLOAT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `detallePedidoPedidoFK_idx` (`pedidoId` ASC) VISIBLE,
  INDEX `detallePedidoProductoFK_idx` (`productoId` ASC) VISIBLE,
  CONSTRAINT `detallePedidoPedidoFK`
    FOREIGN KEY (`pedidoId`)
    REFERENCES `proyectodb`.`Pedidos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `detallePedidoProductoFK`
    FOREIGN KEY (`productoId`)
    REFERENCES `proyectodb`.`Productos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyectodb`.`Pedidos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyectodb`.`Pedidos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `fechaEntrega` DATE NOT NULL,
  `total` FLOAT NOT NULL,
  `usuarioId` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `pedidoUsuarioFK_idx` (`usuarioId` ASC) VISIBLE,
  CONSTRAINT `pedidoUsuarioFK`
    FOREIGN KEY (`usuarioId`)
    REFERENCES `proyectodb`.`Usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyectodb`.`Productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyectodb`.`Productos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `costoUnitario` FLOAT NOT NULL,
  `descripcion` VARCHAR(500) NULL,
  `imagen` BLOB NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyectodb`.`Telefonos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyectodb`.`Telefonos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `usuarioId` INT NOT NULL,
  `telefono` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `telefonos_usuarioFK_idx` (`usuarioId` ASC) VISIBLE,
  CONSTRAINT `telefonos_usuarioFK`
    FOREIGN KEY (`usuarioId`)
    REFERENCES `proyectodb`.`Usuarios` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyectodb`.`Usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyectodb`.`Usuarios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `correo` VARCHAR(45) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `fechaNacimiento` DATE NOT NULL,
  `direccionEntrega` VARCHAR(100) NOT NULL,
  `contrasenia` VARCHAR(45) NOT NULL,
  `activoInactivo` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
